name = "sjtug_theme"
license = "MIT"
licenselink = "//github.com/sjtug/portal/blob/master/LICENSE"
description = "SJTUG Portal theme"
homepage = "//sjtug.org"
tags = ["blog", "disqus", "google analytics", "rss", "syntax highlighting"]
features = ["disqus", "google analytics", "rss", "syntax highlighting", "blog", "pagination", "<sharing options"]
min_version = 0.15

[author]
  name = "sjtug"
  homepage = "//sjtug.org"

[[original]]
  # Ported the stardard theme of the Cactus for Mac static site generator to Jekyll
  name = "Cactus"
  homepage = "//github.com/digitalcraftsman"
  repo = "//github.com/nickbalestra/kactus"

[[original]]
  # Ported the stardard theme of the Cactus for Mac static site generator to Jekyll
  name = "Nick Balestra"
  homepage = "//nick.balestra.ch/"
  repo = "//github.com/nickbalestra/kactus"

[[original]]
  # Original creators of the stardard theme for the Cactus for Mac static site generator
  name = "Cactus for Mac authors"
  homepage = "//cactusformac.com"
  repo = "github.com/koenbok/Cactus"
