# Site settings
baseurl = "https://example.org/"
languageCode = "en-us"
title = "SJTUG - A Joyful Techie User Group"
theme = "sjtug"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "sjtug-portal"

[params]
	name = "SJTUG"
	description = "SJTU *NIX User Group"
	# Enter optionally your twitter account
	twitter = "sjtug"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	news = "Archive"
	softwares = "Mirrors"
	about = "About"
	subscribe = "Contacts"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "SJTUG information automata"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

[taxonomies]
tag = "tags"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/sjtug"
    github   = "https://www.github.com/sjtug"
